#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads. This
script is shipped because three files point at it — `smoke_test.py`'s own
docstring, CONTRIBUTING.md and TROUBLESHOOTING.md — and an instruction
pointing at a file that does not exist is worse than no instruction.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`, and on most of these
sites that works because a fixture is a few hundred bytes of markup. Here the
fixture IS the SSR payload: one ad's entry in `__NEXT_DATA__` is 2-6 KB of
JSON on its own, and a fixture has to carry at least two of them plus the
page's JSON-LD, its pagination block and its tiles, or it stops exercising
the join the parser is built on. Pasting that into a Python source file as
string literals would make `smoke_test.py` unreadable and unreviewable. The
generated JSON sits beside it, is regenerated by this script, and is checked
by the suite for the same properties inline fixtures would be.

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `../captures/` relative to the repo, named as the
`SOURCES` table below expects. They are deliberately NOT in the repository: a
single capture of this site is 440 KB to 1.6 MB, and a real page dump carries
the session that fetched it.

Take them with a browser through a UAE exit — Imperva refuses anything else
— so `--cdp-endpoint` with `country-ae`, and `--dump-html` writes exactly the
bytes the parser was given.

WHAT IT ENFORCES, and why each rule is here
-------------------------------------------
  * every fixture is CUT from a real capture, never hand-written;
  * each one is verified to parse IDENTICALLY to the untrimmed original for
    the ads it keeps — every column, not a sample of them. A trim that drops
    the page's JSON-LD silently empties `brand`, `seller_name` and
    `in_stock`, and a suite built on that fixture would then assert the
    emptiness as correct;
  * personal and credential-shaped material is replaced with obvious
    placeholders BEFORE anything is embedded, and guarded by PATTERNS rather
    than by the literals one capture happened to contain, so the next
    capture's values are caught too. This site's pages carry three kinds:
      - `agent_profile.name`, a real estate agent's own name, 34-35 per
        property page;
      - `user.id`, a per-seller UUID, 25-26 per motors page;
      - the page's Algolia search key, a 32-hex string that reads as a live
        credential to every scanner that looks — including this repo's own
        CI grep.
"""
import json
import os
import pathlib
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from bs4 import BeautifulSoup           # noqa: E402
import product_parser as P              # noqa: E402

HERE = pathlib.Path(os.path.dirname(os.path.abspath(__file__)))
CAPTURES = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else HERE / ".." / "captures")
OUT = HERE / "fixtures_generated.json"

# name -> (capture file, the URL it was fetched from, HTTP status)
SOURCES = {
    "motors_p1":      ("uae_usedcars_p1.html", "https://uae.dubizzle.com/motors/used-cars/", 200),
    "motors_p2":      ("uae_usedcars_p2.html", "https://uae.dubizzle.com/motors/used-cars/?page=2", 200),
    "motors_ar_p1":   ("uae_usedcars_ar_p1.html", "https://uae.dubizzle.com/ar/motors/used-cars/", 200),
    "motors_past_end": ("uae_usedcars_p401.html", "https://uae.dubizzle.com/motors/used-cars/?page=401", 200),
    "property_rent":  ("uae_property_rent_p1.html", "https://uae.dubizzle.com/property-for-rent/residential/apartmentflat/", 200),
    "property_sale":  ("uae_property_sale_apt_p1.html", "https://uae.dubizzle.com/property-for-sale/residential/apartment/", 200),
    "classified":     ("uae_classified_tv_p1.html", "https://uae.dubizzle.com/classified/electronics/televisions/", 200),
    "jobs":           ("uae_jobs_accounting_p1.html", "https://uae.dubizzle.com/jobs/accounting-finance/", 200),
    "community":      ("uae_community_auto_p1.html", "https://uae.dubizzle.com/community/auto-services/", 200),
    "hub_home":       ("uae_home.html", "https://uae.dubizzle.com/", 200),
    "not_found":      ("uae_property_sale_p1.html", "https://uae.dubizzle.com/property-for-sale/residential/apartmentflat/", 404),
    "block_iframe":   ("block_incapsula_iframe.html", "https://uae.dubizzle.com/motors/used-cars/", 403),
    "block_pardon":   ("block_pardon_interruption.html", "https://uae.dubizzle.com/motors/used-cars/", 200),
}

# How many organic ads a listing fixture keeps. Two, because one cannot show
# that `position` increments or that a dedupe has anything to do.
KEEP_ADS = 2

# Patterns, not literals, so the NEXT capture's values are caught too (§10).
SCRUB = [
    # A real person's name, on every property tile.
    (re.compile(r'("agent_profile":\s*\{(?:[^{}]|\{[^{}]*\})*?"name":\s*\{"en":\s*)"[^"]*"(,\s*"ar":\s*)"[^"]*"'),
     r'\1"AGENT NAME REMOVED"\2"AGENT NAME REMOVED"'),
    # A per-seller UUID.
    (re.compile(r'("user":\s*\{"id":\s*)"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"'),
     r'\1"00000000-0000-0000-0000-000000000000"'),
    # The page's own Algolia search key: 32 hex characters, which is exactly
    # the shape a 2Captcha API key takes and exactly what a secret scanner
    # flags.
    (re.compile(r'("(?:x-algolia-api-key|apiKey|API_KEY|CAPTCHA_SITE_KEY)"\s*:\s*)"[^"]{8,}"'),
     r'\1"REDACTED-SEARCH-KEY"'),
    # The page's Sentry instrumentation: a public key, the front-end release
    # SHA and a per-request trace id. The parser reads none of it, it is
    # per-visit rather than per-page, and `sentry-public_key=<32 hex>` is one
    # more string that reads as a credential to every scanner that looks —
    # including this repo's own.
    (re.compile(r'("_sentry(?:Baggage|TraceData)"\s*:\s*)"[^"]*"'),
     r'\1"REDACTED-SENTRY"'),
]

# What a scrubbed fixture must no longer contain. Checked after scrubbing, so
# a pattern that stopped matching the site's current markup fails loudly
# instead of quietly letting the material through.
#
# Deliberately NOT "any 32-hex string": this site's own ad identifier IS 32
# hex characters, it is in every listing URL the site publishes, and 40 to 95
# of them are the legitimate content of any fixture. A blanket pattern
# flagged all of them and would have been switched off within a day, which is
# how a check stops being a check. What is forbidden is a 32-hex (or longer)
# value sitting in a KEY-SHAPED FIELD — which is the shape a 2Captcha API key
# takes and the shape a secret scanner looks for.
FORBIDDEN = [
    # The placeholder is exempt by NAME, not by shape: it is 19 characters of
    # the same alphabet as a real key, so a shape-only rule would flag the
    # very substitution that makes the fixture safe.
    ("a secret-shaped value in a key-shaped field",
     re.compile(r'"(?:[a-zA-Z_-]*(?:api[_-]?key|apikey|secret|token|password|'
                r'client[_-]?key|access[_-]?key|site[_-]?key))"\s*:\s*'
                r'"(?!REDACTED-SEARCH-KEY")[A-Za-z0-9_-]{16,}"', re.I)),
    ("an agent's personal name left in the payload",
     re.compile(r'"agent_profile"\s*:\s*\{(?:[^{}]|\{[^{}]*\})*?"name"\s*:\s*\{"en"\s*:\s*'
                r'"(?!AGENT NAME REMOVED)[^"]+"')),
    ("a per-seller UUID left in the payload",
     re.compile(r'"user"\s*:\s*\{"id"\s*:\s*"(?!00000000-)[0-9a-f-]{36}"')),
]


def _payload_action(data):
    page_props = ((data.get("props") or {}).get("pageProps") or {})
    for action in page_props.get("reduxWrapperActionsGIPP") or []:
        if isinstance(action, dict) and action.get("type") == P._LISTINGS_ACTION:
            return action
    return None


def trim(html, keep_ads=KEEP_ADS):
    """Cut a capture down to the first `keep_ads` ads and their markup.

    Keeps, in order of what it costs to lose: the payload action with its
    `pagination` block, the JSON-LD ItemList entries for the SAME ads, the
    tiles those ads render, and enough asset-host references for
    `served_by_dubizzle` to see the page as served.
    """
    m = P._NEXT_DATA_RE.search(html)
    if not m:
        return None, []
    data = json.loads(m.group(1))
    action = _payload_action(data)
    if action is None:
        return None, []
    payload = action["payload"]
    hits = (payload.get("hits") or [])[:keep_ads]
    promoted = (payload.get("cotwListings") or [])[:1]
    payload["hits"] = hits
    payload["cotwListings"] = promoted
    for key in ("promotedAds", "developerListings", "developerListingPageData",
                "masterProjectListing", "areaPrimeSlotListing"):
        payload.pop(key, None)
    # Drop every action but the grid one — the rest is feature flags, A/B
    # buckets and SEO rails, and none of it is read.
    data["props"]["pageProps"]["reduxWrapperActionsGIPP"] = [action]
    data["props"]["pageProps"].pop("props", None)

    kept_urls = {P.sku_from_url(P._en(h.get("absolute_url")) or "")
                 for h in hits + promoted}
    kept_urls.discard(None)

    soup = BeautifulSoup(html, "html.parser")
    parts = []
    # The page's own JSON-LD, reduced to the ads we kept.
    for tag in soup.find_all("script", attrs={"type": "application/ld+json"}):
        try:
            block = json.loads(tag.string or "")
        except (ValueError, TypeError):
            continue
        main = block.get("mainEntity") if isinstance(block, dict) else None
        if isinstance(main, dict) and main.get("itemListElement"):
            main["itemListElement"] = [
                e for e in main["itemListElement"]
                if P.sku_from_url((e.get("item") or {}).get("url") or "") in kept_urls]
        parts.append('<script type="application/ld+json">%s</script>'
                     % json.dumps(block, ensure_ascii=False))
    # The tiles for those ads.
    seen = set()
    for anchor in soup.select("a[href]"):
        sku = P.sku_from_url(P._absolutise(anchor.get("href") or "",
                                           "https://uae.dubizzle.com/"))
        if sku in kept_urls and sku not in seen:
            seen.add(sku)
            parts.append(str(P._tile_of(anchor)))

    # The site's own pagination links are part of what a fixture has to
    # carry: page_flow's first and strongest selector layer is
    # `link[rel="next"]`, and a fixture that dropped it would let that layer
    # rot untested.
    rels = "".join(str(t) for t in soup.find_all(
        "link", attrs={"rel": lambda v: v and any(
            k in v for k in ("next", "prev", "canonical", "alternate"))}))
    head = ('<!doctype html><html lang="%s"><head>'
            '<link rel="preconnect" href="https://static.dubizzle.com">'
            '<link rel="icon" href="https://static.dubizzle.com/favicon.ico">'
            '%s<title>%s</title>'
            % ((soup.html.get("lang") if soup.html else "en") or "en", rels,
               soup.title.get_text(strip=True) if soup.title else ""))
    nxt = ('<script id="__NEXT_DATA__" type="application/json">%s</script>'
           % json.dumps(data, ensure_ascii=False))
    trimmed = head + "</head><body>" + "".join(parts) + nxt + "</body></html>"
    return trimmed, sorted(kept_urls)


def scrub(text):
    for pattern, replacement in SCRUB:
        text = pattern.sub(replacement, text)
    return text


def rows_by_sku(html, url, status=200):
    # The page number comes from the URL, exactly as an engine passes it —
    # pinning with the default 1 and reading back with the URL's 2 made the
    # `page` column mismatch on every page-2 fixture.
    return {r.sku: r
            for r in P.parse_products(html, url,
                                      page=P.page_number_from_url(url))}


def main():
    if not CAPTURES.is_dir():
        sys.exit("no captures at %s. Take some with --dump-html through a UAE "
                 "exit (--cdp-endpoint with country-ae), or pass their "
                 "directory as the first argument." % CAPTURES)

    out = {}
    problems = 0
    for name, (filename, url, status) in SOURCES.items():
        path = CAPTURES / filename
        if not path.is_file():
            print("MISSING  %-16s %s" % (name, path))
            problems += 1
            continue
        original = path.read_text()

        if name.startswith("block_") or name in ("hub_home", "not_found"):
            # No grid to trim. These fixtures exist for `detect_page_state`,
            # so they are kept whole — and they are small: 1 KB, 5 KB, 437 KB
            # and 625 KB. The two large ones are cut down to their <head> and
            # their asset references, which is all the classifier reads.
            body = original if len(original) < 20000 else _shrink_non_grid(original)
            body = scrub(body)
            out[name] = {"url": url, "status": status, "html": body,
                         "expect_state": P.detect_page_state(body, status, url),
                         "expect_rows": len(P.parse_products(body, url))}
            print("kept    %-16s %6d bytes  state=%s"
                  % (name, len(body), out[name]["expect_state"]))
            continue

        trimmed, kept = trim(original)
        if trimmed is None:
            print("NO PAYLOAD %-14s %s" % (name, filename))
            problems += 1
            continue
        trimmed = scrub(trimmed)

        # The check that earns this script's existence: the trim must parse
        # identically to the untrimmed capture, column for column.
        before = rows_by_sku(original, url)
        after = rows_by_sku(trimmed, url)
        if set(after) != set(kept):
            print("TRIM LOST ADS %-11s kept=%d parsed=%d" % (name, len(kept), len(after)))
            problems += 1
        for sku in sorted(set(after) & set(before)):
            a, b = before[sku], after[sku]
            for f in a.__dataclass_fields__:
                if f == "scraped_at":
                    continue
                # `position` is a fact about the PAGE, not about the ad, and
                # the promoted Car of the Week is emitted after the organic
                # results — so it is position 26 on a full page of 25 and
                # position 3 on a fixture of 2. That is the parser working,
                # not the trim losing something, and asserting it would make
                # the check fail for the one row it is least worried about.
                # The organic rows' positions ARE compared, and they hold.
                if f == "position" and a.listing_kind == "car_of_the_week":
                    continue
                if getattr(a, f) != getattr(b, f):
                    print("TRIM CHANGED %-12s %s.%s: %r -> %r"
                          % (name, sku[-24:], f, getattr(a, f), getattr(b, f)))
                    problems += 1

        for why, pattern in FORBIDDEN:
            found = pattern.findall(trimmed)
            if found:
                print("NOT SCRUBBED %-12s %s: %d occurrence(s), e.g. %r"
                      % (name, why, len(found), found[0][:40]))
                problems += 1

        out[name] = {
            "url": url,
            "status": status,
            "html": trimmed,
            "expect_state": P.detect_page_state(trimmed, status, url),
            "expect_rows": len(after),
            "expect_skus": sorted(after),
            # Pinned VALUES, not coverage (§10): a column can be 100%
            # populated and entirely wrong.
            "expect": {sku: {f: getattr(after[sku], f)
                             for f in after[sku].__dataclass_fields__
                             if f != "scraped_at"}
                       for sku in sorted(after)},
            "expect_total_results": P.total_results(trimmed),
            "expect_total_pages": P.total_pages(trimmed, url),
            "expect_index": P.search_header(trimmed),
        }
        print("cut     %-16s %6d bytes  %d ad(s)  state=%s"
              % (name, len(trimmed), len(after), out[name]["expect_state"]))

    if problems:
        sys.exit("%d problem(s); nothing written." % problems)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1))
    print("\nwrote %s (%d fixtures, %d KB)"
          % (OUT.name, len(out), OUT.stat().st_size // 1024))


def _shrink_non_grid(html):
    """A no-grid page cut to what the classifier actually reads.

    Its <head>, its asset references and its own no-results sentence — not
    the 600 KB of promo rails around them.
    """
    soup = BeautifulSoup(html, "html.parser")
    title = soup.title.get_text(strip=True) if soup.title else ""
    assets = re.findall(r'https://(?:static|dbz-images)\.dubizzle\.com/[^"\'\s]{0,80}', html)[:6]
    sentence = ""
    for marker in P.NO_RESULTS_MARKERS:
        if marker in html:
            sentence = marker
            break
    nxt = P._NEXT_DATA_RE.search(html)
    payload = ""
    if nxt:
        try:
            data = json.loads(nxt.group(1))
            data["props"]["pageProps"]["reduxWrapperActionsGIPP"] = []
            data["props"]["pageProps"].pop("props", None)
            payload = ('<script id="__NEXT_DATA__" type="application/json">%s</script>'
                       % json.dumps(data, ensure_ascii=False))
        except (ValueError, KeyError, TypeError):
            payload = ""
    links = "".join('<link rel="preconnect" href="%s">' % a for a in assets)
    return ('<!doctype html><html lang="en"><head><title>%s</title>%s</head>'
            '<body><p>%s</p>%s</body></html>' % (title, links, sentence, payload))


def cut_sample(run="live_p1.json"):
    """Cut `sample_output.{json,csv}` from a real run's output.

    Shipped here rather than as a second script because CI checks the sample
    against the schema on every push (§10) and a reader who changes a column
    needs one obvious way to regenerate it:

        python3 playwright_scraper.py --url ... --out live_p1 --format json
        python3 make_fixtures.py --sample live_p1.json

    Ten rows: nine organic and the promoted slot, so the sample shows both
    kinds of row the scraper can produce rather than only the common one.
    """
    import csv  # noqa: F401  (write_csv needs it via output_writer)
    from output_writer import Product, write_csv
    rows = json.loads(pathlib.Path(run).read_text())
    page1 = [r for r in rows if r.get("page") == 1]
    sample = [r for r in page1 if r.get("listing_kind") == "organic"][:9]
    sample += [r for r in page1 if r.get("listing_kind") == "car_of_the_week"][:1]
    if not sample:
        sys.exit("no rows in %s to cut a sample from" % run)
    pathlib.Path("sample_output.json").write_text(
        json.dumps(sample, ensure_ascii=False, indent=2) + "\n")
    write_csv([Product(**r) for r in sample], "sample_output.csv")
    print("wrote sample_output.{json,csv}: %d rows, kinds=%s"
          % (len(sample), sorted({r["listing_kind"] for r in sample})))


if __name__ == "__main__":
    if "--sample" in sys.argv:
        i = sys.argv.index("--sample")
        cut_sample(sys.argv[i + 1] if len(sys.argv) > i + 1 else "live_p1.json")
    else:
        main()
